language: minimal
services: docker
env:
  - image=perl:5.30
  - image=perl:5.30-threaded
  - image=perl:5.28
  - image=perl:5.28-threaded
  - image=perl:5.26
  - image=perl:5.26-threaded
  - image=perl:5.24
  - image=perl:5.24-threaded
  - image=perl:5.22
  - image=perl:5.22-threaded
  - image=perl:5.20
  - image=perl:5.20-threaded
before_install:
  - docker pull $image
  - docker run $image perl -V
script:
  - |
    docker run --init -it -v $PWD:/app -w /app $image bash -c '
    set -euxo pipefail
    apt update &&
    apt install -y llvm-dev libclang-dev clang &&
    curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh &&
    sh rustup.sh -y &&
    source $HOME/.cargo/env &&
    cd /app &&
    cargo clean &&
    cargo build -vv &&
    cargo test --all'
