name: Rust

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-dev libclang-dev clang libnsl-dev

    - name: Set up Perl ${{ matrix.perl-version }}
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl-version }}
        multi-thread: ${{ matrix.threaded }}

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all --examples

    strategy:
      fail-fast: false
      matrix:
        threaded: [ true, false ]
        perl-version:
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
          - '5.36'
          - '5.38'
          - '5.40'
          - '5'
        target:
          - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
