name: Rust

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: apt update && apt install -y llvm-dev libclang-dev clang && curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh && sh ./rustup.sh -y
    - name: Build
      run: source $HOME/.cargo/env && cargo build --verbose
    - name: Run tests
      run: source $HOME/.cargo/env && cargo test --verbose --all
      
    strategy:
      matrix:
        perl-version:
          - '5.10'
          - '5.10-threaded'
          - '5.16'
          - '5.16-threaded'
          - '5.30'
          - '5.30-threaded'
          - '5.32'
          - '5.32-threaded'
          - '5.34'
          - '5.34-threaded'
          - 'latest'

    container:
      image: perl:${{ matrix.perl-version }}

      
